name: build

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  build-job:
    name: Build Latest
    runs-on: ubuntu-latest
    container:
      image: perldocker/perl-tester:latest
    env:
      ORACLEV: 19.6
      ORACLEDBV: 11.2
      ORACLE_USERID: kermit/foobar
      ORACLE_USERID_2: mspiggy/barfoo
      ORACLE_DSN: 'dbi:Oracle://localhost:1521/XE'
    steps:
      - uses: actions/checkout@v2
      - run: apt-get install -y sudo libaio1 libaio-dev net-tools bc
# FYI Oracle XE only comes in utf8, so we can't run USASCII version of tests
      - run: df -h; cat /proc/meminfo; uname -a; cat /etc/*-release
#      - run: sudo -E maint/scripts/01_install_oracle_xe.bash
#      - run: tail -n +1 /u01/app/oracle/product/11.2.0/xe/config/log/*
#      - run: sudo -E maint/scripts/02_install_oracle_instantclient.bash
#      - run: . /etc/profile
#      - run: cpanm DBI
#      - run: cpanm Test::NoWarnings
#      - run: perl Makefile.PL && make && make test
